# Generated by Django 3.0.6 on 2020-05-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressinfo',
            options={'verbose_name': '省市县地址信息', 'verbose_name_plural': '省市县地址信息'},
        ),
        migrations.AlterUniqueTogether(
            name='addressinfo',
            unique_together={('address', 'note')},
        ),
        migrations.AlterModelTable(
            name='addressinfo',
            table='address',
        ),
    ]
